clockboard/urls.py
from django.urls import path

from . import views

app_name = 'clockboard'


urlpatterns = [
    path('', views.index, name='index'),
    path('clocks/', views.dashboard, name='dashboard'),
    path('clocks/<int:clock_id>/reset/', views.reset_clock, name='reset_clock'),
    path('clocks/new/', views.new_clock, name='new_clock'),
]

clockboard/models.py
from django.db import models
from django.utils import timezone
from django.conf import settings


class General(models.Model):
    class Meta:
        managed = False
        default_permissions = ()
        permissions = (
            ('can_see_clocks', "Can see clocks"),
            ('can_add_clocks', "Can add clocks"),
        )


class Clock(models.Model):
    name = models.CharField(max_length=255, unique=True)
    last_reset = models.DateTimeField(default=timezone.now)
    last_reset_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.RESTRICT, related_name='+')
    is_active = models.BooleanField(default=True)

    class Meta:
        default_permissions = ()

    def __str__(self):
        return self.name


class ClockLog(models.Model):
    clock = models.ForeignKey(Clock, on_delete=models.CASCADE, related_name='history')
    reset_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.RESTRICT, related_name='+')
    timestamp = models.DateTimeField(default=timezone.now)
    comment = models.TextField(blank=True, null=True)
    num_involved = models.IntegerField()

    class Meta:
        default_permissions = ()

    def __str__(self):
        return f"{self.clock} - {self.timestamp}"

clockboard/forms.py
from django import forms

from .models import Clock


class ResetClockForm(forms.Form):
    num_involved = forms.IntegerField(min_value=1, label='Number of people involved')
    comment = forms.CharField(required=False, widget=forms.Textarea)


class NewClockForm(forms.ModelForm):
    class Meta:
        model = Clock
        fields = ['name']
        labels = {
            'name': 'Clock name',
        }

clockboard/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required, permission_required
from django.utils import timezone
from django.db import transaction
from django.template.loader import render_to_string

from .models import Clock, ClockLog
from .forms import ResetClockForm, NewClockForm


def dashboard_clocks(request):
    clocks = (
        Clock.objects
        .filter(is_active=True)
        .select_related('last_reset_by__profile__main_character')
    )

    context = {
        'clocks': clocks,
    }

    return render_to_string('clockboard/dashboard_panel.html', context=context, request=request)


@login_required
@permission_required('clockboard.can_see_clocks')
def index(request):
    return redirect('clockboard:dashboard')


@login_required
@permission_required('clockboard.can_see_clocks')
def dashboard(request):
    clocks = (
        Clock.objects
        .filter(is_active=True)
        .select_related('last_reset_by__profile__main_character')
    )

    context = {
        'clocks': clocks,
    }

    return render(request, 'clockboard/clock_board.html', context=context)


@login_required
@permission_required('clockboard.can_see_clocks')
def reset_clock(request, clock_id: int):
    clock = get_object_or_404(Clock, pk=clock_id)

    if request.method == 'POST':
        form = ResetClockForm(request.POST)
        if form.is_valid():
            with transaction.atomic():
                clock.last_reset_by = request.user
                clock.last_reset = timezone.now()
                clock.save()

                ClockLog.objects.create(
                    clock=clock,
                    reset_by=request.user,
                    comment=form.cleaned_data['comment'],
                    num_involved=form.cleaned_data['num_involved'],
                    timestamp=clock.last_reset,
                )

            return redirect('clockboard:dashboard')
    else:
        form = ResetClockForm()

    context = {
        'form': form,
    }

    return render(request, 'clockboard/reset_clock.html', context=context)


@login_required
@permission_required('clockboard.can_add_clocks')
def new_clock(request):
    if request.method == 'POST':
        form = NewClockForm(request.POST)
        if form.is_valid():
            clock = form.save(commit=False)
            clock.last_reset_by = request.user
            clock.save()

            return redirect('clockboard:dashboard')
    else:
        form = NewClockForm()

    context = {
        'form': form,
    }

    return render(request, 'clockboard/new_clock.html', context=context)

clockboard/templates/clockboard/base.html
{% extends 'allianceauth/base-bs5.html' %}

{% block page_title %}Clock Board{% endblock page_title %}

{% block content %}
    <div class="row">
        {% block clockboardcontent %}{% endblock clockboardcontent %}
    </div>
{% endblock content %}

clockboard/templates/clockboard/clock_board.html
{% extends "clockboard/base.html" %}

{% block clockboardcontent %}
    <h1 class="page-header text-center">Clock Board</h1>
    <div class="row justify-content-evenly mt-3">
        {% include "clockboard/clocks.html" %}
        {% if perms.clockboard.can_add_clocks %}
            <div class="col-12 col-lg-6 col-xl-3">
                <div class="card h-100">
                    <div class="card-body">
                        <div class="d-flex justify-content-center align-items-center h-100">
                            <a href="{% url "clockboard:new_clock" %}" class="btn btn-primary">
                                <i class="fa-solid fa-plus"></i>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        {% endif %}
    </div>
{% endblock clockboardcontent %}

clockboard/templates/clockboard/clocks.html
{% load evelinks %}
{% load static %}

{% for clock in clocks %}
    <div class="col-12 col-lg-6 col-xl-3">
        <div class="card h-100 text-center">
            <div class="card-header">{{ clock.name }}</div>
            <div class="card-body">
                <h4 class="card-title">
                    <i class="fa-regular fa-clock"></i>
                    <span class="ms-3" id="clock{{ clock.pk }}"></span>
                </h4>
                <p class="card-text mt-3">
                    <img src="{{ clock.last_reset_by.profile.main_character|character_portrait_url:32 }}" class="rounded me-2">
                    {{ clock.last_reset_by.profile.main_character.character_name }}
                </p>
                <div class="d-flex justify-content-center">
                    <a href="{% url "clockboard:reset_clock" clock.pk %}" class="btn btn-primary">Reset</a>
                </div>
            </div>
        </div>
    </div>
{% endfor %}

{% include 'bundles/moment-js.html' %}
{% include 'bundles/timers-js.html' %}
<script type="application/javascript">
    var clocks = [
        {% for clock in clocks %}
            {
                id: "{{ clock.pk }}",
                last_reset: moment("{{ clock.last_reset|date:'c' }}"),
            },
        {% endfor %}
    ];
</script>
<script src="{% static "clockboard/js/clocks.js" %}"></script>
<script type="application/javascript">
    updateAllClocks();
    setInterval(updateAllClocks, 1000);
</script>

clockboard/templates/clockboard/dashboard_panel.html
{% if clocks|length > 0 %}
    <div class="col-12 align-self-stretch p-2 ps-0 pe-0 ps-xl-0 pe-xl-2">
        <div class="row justify-content-evenly">
            {% include "clockboard/clocks.html" %}
        </div>
    </div>
{% endif %}

clockboard/templates/clockboard/new_clock.html
{% extends "clockboard/base.html" %}
{% load django_bootstrap5 %}

{% block clockboardcontent %}
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <form method="post"> {% csrf_token %}
                    {% bootstrap_form form %}
                    <button type="submit" class="btn btn-primary">Add</button>
                </form>
            </div>
        </div>
    </div>
{% endblock clockboardcontent %}

clockboard/templates/clockboard/reset_clock.html
{% extends "clockboard/base.html" %}
{% load django_bootstrap5 %}

{% block clockboardcontent %}
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <form method="post"> {% csrf_token %}
                    {% bootstrap_form form %}
                    <button type="submit" class="btn btn-primary">Reset</button>
                </form>
            </div>
        </div>
    </div>
{% endblock clockboardcontent %}